check:
  - thoth-build
build:
  build-stratergy: "Dockerfile"
  registry: "quay.io"
  registry-org: "harshad16"
  registry-project: "odh-manifests"
  registry-secret: "thoth-station-thoth-pusher-secret"
